dist: trusty
sudo: false


language: python

python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - 'pip install pipenv'
  - make install
# command to run tests
script:
  - make test